# 목차
<br>

[part.1 이동](#name) <br>
[part.2 이동](#name) <br>
[part.3 이동](#name) <br>
[part.4 이동](#name) <br>

# Part.1

## numpy, pandas와 친해지기

### 개요
1. numpy
1. pandas
3. torch로 vector, matrix 등 만들어보기

### 1. numpy, array, matrix 등

In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
import numpy as np

In [3]:
# !pip install ipykernel

리스트, 행렬 선언

In [4]:
# list_name(변수명 설정) = ["item-1", "item-2", ..., "item-n"]

a = [1, 2, 3]
b = ["a", "b", "c"]
c = [["a"], ["a", "b"], ["a", "c"], ["a", "b", "c"]]

print(a)
print(b)
print(c)

[1, 2, 3]
['a', 'b', 'c']
[['a'], ['a', 'b'], ['a', 'c'], ['a', 'b', 'c']]


In [5]:
# append()로 list에 item 추가하기
c.append('new_item')
c.append(['new_item_list'])

print(c)

[['a'], ['a', 'b'], ['a', 'c'], ['a', 'b', 'c'], 'new_item', ['new_item_list']]


In [6]:
a = np.array([1,2,3])
b = np.array(["a","b","c"])
c = np.array([["a"], ['a','b'], ['a','c'],['a','b','c']])

print(a)
print(b)
print(c)

[1 2 3]
['a' 'b' 'c']
[list(['a']) list(['a', 'b']) list(['a', 'c']) list(['a', 'b', 'c'])]


In [7]:
# 배열(or 행렬)을 1로 채우기

print(np.ones((1,5)))
print(np.ones((3,2)))

[[1. 1. 1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [8]:
# 배열(or 행렬)을 0으로 채우기

print(np.zeros((1,5)))
print(np.zeros((3,2)))

[[0. 0. 0. 0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [9]:
# 주어진 범위 안에서 순차적으로 증가하는 리스트 만들기
# np.arange([start,] stop, [step, ], dtype-None)

print(np.arange(10))
print(np.arange(3, 7, dtype=np.float))
print(np.arange(3, 10, 2))

[0 1 2 3 4 5 6 7 8 9]
[3. 4. 5. 6.]
[3 5 7 9]


In [10]:
# 행렬 선언하기
mat1 = np.array([[1,2,3],[4,5,6]])

# random으로 matrix 만들기
mat2 = np.random.randint(low=1, high=10, size=(3,2))
mat3 = np.random.rand(3,2)

print(mat1)
print(mat2)
print(mat3)

[[1 2 3]
 [4 5 6]]
[[4 8]
 [1 4]
 [2 4]]
[[0.52759224 0.77052393]
 [0.46292174 0.3695234 ]
 [0.47315466 0.5997007 ]]


리스트 인덱싱(Indexing) & 슬라이싱(Slicing)

In [11]:
# Indexing
a = [1, 3, 5, 7, 9, 11]
print(a[2], a[5], a[-1])

5 11 11


In [12]:
# Slicing
b = [2,4,6,8,10]
print(b[2:])
print(b[:2])
print(b[:])

[6, 8, 10]
[2, 4]
[2, 4, 6, 8, 10]


numpy의 reshape (PyToch의 view와 비교)

In [13]:
# (row, column)
mat1 = np.random.rand(6,3)
print(mat1)

[[0.46734729 0.41904621 0.47241685]
 [0.06558019 0.95004833 0.67169836]
 [0.38978724 0.79170902 0.04191297]
 [0.71607345 0.26774251 0.95486323]
 [0.22806149 0.9672031  0.58236147]
 [0.96546965 0.44557136 0.11771021]]


In [14]:
# -1: all
print(mat1.reshape(1, -1).shape)
print(mat1.reshape(1, -1))
print("=====")
print(mat1.reshape(-1,1).shape)
print(mat1.reshape(-1,1))

(1, 18)
[[0.46734729 0.41904621 0.47241685 0.06558019 0.95004833 0.67169836
  0.38978724 0.79170902 0.04191297 0.71607345 0.26774251 0.95486323
  0.22806149 0.9672031  0.58236147 0.96546965 0.44557136 0.11771021]]
=====
(18, 1)
[[0.46734729]
 [0.41904621]
 [0.47241685]
 [0.06558019]
 [0.95004833]
 [0.67169836]
 [0.38978724]
 [0.79170902]
 [0.04191297]
 [0.71607345]
 [0.26774251]
 [0.95486323]
 [0.22806149]
 [0.9672031 ]
 [0.58236147]
 [0.96546965]
 [0.44557136]
 [0.11771021]]


In [15]:
print(mat1.reshape(2,9).shape)
print(mat1.reshape(9, 2))

(2, 9)
[[0.46734729 0.41904621]
 [0.47241685 0.06558019]
 [0.95004833 0.67169836]
 [0.38978724 0.79170902]
 [0.04191297 0.71607345]
 [0.26774251 0.95486323]
 [0.22806149 0.9672031 ]
 [0.58236147 0.96546965]
 [0.44557136 0.11771021]]


In [16]:
mat1.reshape(3,6)

array([[0.46734729, 0.41904621, 0.47241685, 0.06558019, 0.95004833,
        0.67169836],
       [0.38978724, 0.79170902, 0.04191297, 0.71607345, 0.26774251,
        0.95486323],
       [0.22806149, 0.9672031 , 0.58236147, 0.96546965, 0.44557136,
        0.11771021]])

In [17]:
# tensor 형태로 나타내기
print(mat1.reshape(3,2,3).shape)
print(mat1.reshape(3,2,3))

(3, 2, 3)
[[[0.46734729 0.41904621 0.47241685]
  [0.06558019 0.95004833 0.67169836]]

 [[0.38978724 0.79170902 0.04191297]
  [0.71607345 0.26774251 0.95486323]]

 [[0.22806149 0.9672031  0.58236147]
  [0.96546965 0.44557136 0.11771021]]]


matrix 또는 tensor 형태에서도 slicing이 가능합니다!

In [18]:
mat2 = np.arange(24).reshape(-1, 4)
print(mat2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [19]:
mat2[:1,:3]

array([[0, 1, 2]])

In [20]:
mat2[3, 0:2]

array([12, 13])

matrix 또는 tensor 형태에서도 slicing이 가능하다.

In [21]:
mat2 = np.arange(24).reshape(-1,4)
print(mat2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [22]:
mat2[:1,:3]

array([[0, 1, 2]])

In [23]:
mat2[3,0:2]

array([12, 13])

Math Arithmetic Operations(사칙연산)

In [24]:
x = np.array([[1,3,5],[7,9,11],[13,15,17]])
y = np.array([[2,4,6],[8,10,12],[14,16,18]])

print(x)
print(y)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [25]:
x+y

array([[ 3,  7, 11],
       [15, 19, 23],
       [27, 31, 35]])

In [26]:
x-y

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [27]:
x*y

array([[  2,  12,  30],
       [ 56,  90, 132],
       [182, 240, 306]])

In [28]:
x/y

array([[0.5       , 0.75      , 0.83333333],
       [0.875     , 0.9       , 0.91666667],
       [0.92857143, 0.9375    , 0.94444444]])

In [29]:
print(x**2)
print(np.power(x,2))

[[  1   9  25]
 [ 49  81 121]
 [169 225 289]]
[[  1   9  25]
 [ 49  81 121]
 [169 225 289]]


In [30]:
np.dot(x,y)

array([[ 96, 114, 132],
       [240, 294, 348],
       [384, 474, 564]])

In [31]:
np.sqrt(x)

array([[1.        , 1.73205081, 2.23606798],
       [2.64575131, 3.        , 3.31662479],
       [3.60555128, 3.87298335, 4.12310563]])

In [32]:
# More on matrix operation
z1 = np.array([[2,2,2]])
z2 = np.array([[2,2]])

x*z1

array([[ 2,  6, 10],
       [14, 18, 22],
       [26, 30, 34]])

In [33]:
print(z2.shape)
print(x.shape)

print(x*z2) # 행렬 길이가 안맞음

(1, 2)
(3, 3)


ValueError: operands could not be broadcast together with shapes (3,3) (1,2) 

In [38]:
# 합
print(x)
print(x.sum(axis = 0))

print(x.sum(axis = 1))

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
[21 27 33]
[ 9 27 45]


In [39]:
# 평균
print(x)
print(x.mean(axis=0))
print(x.mean(axis=1))

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
[ 7.  9. 11.]
[ 3.  9. 15.]


In [40]:
# 표준편차
print(x)
print(x.std(axis=0))
print(x.std(axis=1))

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
[4.89897949 4.89897949 4.89897949]
[1.63299316 1.63299316 1.63299316]


In [41]:
print(x.T)
print(np.dot(x, z1.T))

[[ 1  7 13]
 [ 3  9 15]
 [ 5 11 17]]
[[18]
 [54]
 [90]]


### Other operations

In [42]:
xx = np.random.rand(15)
print(xx)

[0.37638235 0.15638843 0.46679425 0.24369576 0.08218502 0.53312617
 0.13741304 0.47176516 0.94507419 0.48207777 0.32720779 0.36420065
 0.9865246  0.52693168 0.23937865]


In [43]:
print(xx)
print(xx.argsort())
xx.sort()
print(xx)

[0.37638235 0.15638843 0.46679425 0.24369576 0.08218502 0.53312617
 0.13741304 0.47176516 0.94507419 0.48207777 0.32720779 0.36420065
 0.9865246  0.52693168 0.23937865]
[ 4  6  1 14  3 10 11  0  2  7  9 13  5  8 12]
[0.08218502 0.13741304 0.15638843 0.23937865 0.24369576 0.32720779
 0.36420065 0.37638235 0.46679425 0.47176516 0.48207777 0.52693168
 0.53312617 0.94507419 0.9865246 ]


## 2. Pandas

In [44]:
import pandas as pd

### Pandas Series 만들기

- pandas series는 1차원 데이터 집합

In [ ]:
pd_Series = pd.Series(index=['a','b','c','d','e'], data=[1,2,3,4,5])
pd_Series

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
# Pandas Series의 기초정보
print('차원', pd_Series.ndim)
print('형태', pd_Series.shape)
print('총 원소의 수', pd_Series.size)

print('값', pd_Series.values)
print('인덱스', pd_Series.index)

차원 1
형태 (5,)
총 원소의 수 5
값 [1 2 3 4 5]
인덱스 Index(['a', 'b', 'c', 'd', 'e'], dtype='object')


### index를 활용한 데이터 탐색

In [34]:
# loc(index를 활용하여 access), iloc(integer location)

print(pd_Series.loc['a'])
print(pd_Series.iloc[0])

print(pd_Series.loc[['a','c']])
print(pd_Series.iloc[[0,2]])

NameError: name 'pd_Series' is not defined

### 데이터 삭제

In [ ]:
pd_Series.drop('b')

a    1
c    3
d    4
e    5
dtype: int64

In [ ]:
print(pd_Series)
pd_Series.drop('b', inplace=True)
print(pd_Series)

a    1
b    2
c    3
d    4
e    5
dtype: int64
a    1
c    3
d    4
e    5
dtype: int64


### Pandas Dataframe 만들기

- 2차원 데이터의 집합. 행렬과 비슷하게 row와 column을 갖고 있다.

In [35]:
data = {
    'A' : np.arange(15),
    'B' : np.random.randint(low=0, high=15, size=(15)),
    'C' : np.random.rand(15)
}

data_df = pd.DataFrame(data)

NameError: name 'pd' is not defined

In [ ]:
data_df.head()

A   B         C
0  0  11  0.290634
1  1   2  0.924054
2  2   4  0.076891
3  3   6  0.721175
4  4  11  0.114768

In [ ]:
data_df.tail()

A   B         C
10  10   6  0.904234
11  11   1  0.277852
12  12   2  0.224226
13  13  10  0.221617
14  14  11  0.530413

In [ ]:
data_df.shape

(15, 3)

### Indexing and Slicing

In [36]:
data_df[1:3]

NameError: name 'data_df' is not defined

In [37]:
data_df.loc[1]

NameError: name 'data_df' is not defined

In [77]:
data_df.loc[1]['C']

0.9240537479909375

### Add, Remove and etc

In [79]:
data_df['D'] = data_df['A'] >= 5
data_df

A   B         C      D
0    0  11  0.290634  False
1    1   2  0.924054  False
2    2   4  0.076891  False
3    3   6  0.721175  False
4    4  11  0.114768  False
5    5   3  0.928272   True
6    6  13  0.978921   True
7    7  13  0.022895   True
8    8   0  0.970744   True
9    9   9  0.147087   True
10  10   6  0.904234   True
11  11   1  0.277852   True
12  12   2  0.224226   True
13  13  10  0.221617   True
14  14  11  0.530413   True

In [80]:
data_df.drop('D', axis=1, inplace=True)

In [81]:
data_df.sort_index(axis=0, ascending=False)

A   B         C
14  14  11  0.530413
13  13  10  0.221617
12  12   2  0.224226
11  11   1  0.277852
10  10   6  0.904234
9    9   9  0.147087
8    8   0  0.970744
7    7  13  0.022895
6    6  13  0.978921
5    5   3  0.928272
4    4  11  0.114768
3    3   6  0.721175
2    2   4  0.076891
1    1   2  0.924054
0    0  11  0.290634

# Part.2

## PyTorch Basics

### PyTorch
- provides multidimensional arrays
- tensors, and an extensive library of operations on them

In [82]:
# !pip install torch
import torch

### 1. Tensor란? Tensor 만들기

- Tensors : Multidimensional arrays

In [83]:
# Create a torch.Tensor object with the given data. It is a 1D vector
V_data = [1., 2., 3.]
V = torch.Tensor(V_data)
print(V)

# Creates a matrix
M_data = [[1., 2., 3.], [4., 5., 6]]
M = torch.Tensor(M_data)
print(M)

# Create a 3D tensor of size 2x2x2
T_data = [[[1., 2.],[3.,4.]],[[5.,6.],[7.,8.]]]
T = torch.Tensor(T_data)
print(T)

tensor([1., 2., 3.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [84]:
# torch.ones : tensor를 size에 맞게 1로 채운다
a = torch.ones(3)
print(a)

b = torch.ones(2, 3)
print(b)

tensor([1., 1., 1.])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [85]:
# torch.zeros : tensor를 size에 맞게 0으로 채운다
c = torch.zeros(4)
print(c)

d = torch.zeros(5, 2, 3)
print(d)

tensor([0., 0., 0., 0.])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [88]:
# 초기화하면서 현재 메모리에 존재하는 값
x = torch.empty(5,3)
print(x)

x = torch.rand(5,3)
print(x)

tensor([[-3.2361e+08,  6.5581e-43, -3.2361e+08],
        [ 6.5581e-43, -3.2361e+08,  6.5581e-43],
        [-3.2361e+08,  6.5581e-43, -3.2361e+08],
        [ 6.5581e-43, -3.2361e+08,  6.5581e-43],
        [-3.2361e+08,  6.5581e-43, -3.2361e+08]])
tensor([[0.0689, 0.1150, 0.1851],
        [0.2197, 0.1082, 0.2149],
        [0.4311, 0.5361, 0.6163],
        [0.1869, 0.3795, 0.6267],
        [0.1596, 0.4391, 0.2238]])


In [89]:
# torch.rand : 랜덤 숫자로 tensor를 채운다
rand_points = torch.rand(4, dtype=torch.double)
print(rand_points)

rand_points_2 = torch.rand(2, 3, dtype=torch.float)
print(rand_points_2)

tensor([0.3087, 0.8514, 0.4506, 0.1705], dtype=torch.float64)
tensor([[0.3315, 0.0989, 0.7346],
        [0.7919, 0.4963, 0.6042]])


In [90]:
# 행렬 사이즈
print(rand_points_2.size())

torch.Size([2, 3])


### 2. Indexing Tensors

In [92]:
temp = torch.Tensor([0, 1, 2, 3, 4, 5, 6, 7])

print(temp[:]) # tensor element 전체
print(temp[1:4]) # index 1과 4 사이의 원소들 출력
print(temp[1:]) # index 1부터의 원소들 출력
print(temp[:4]) # index 4까지의 원소들 출력
print(temp[-1]) # 뒤에서 첫번째 원소 출력
print(temp[:-1]) # index -1 = 뒤에서부터 index 1에 해당하는 원소까지만 출력
print(temp[1:6:2]) # index 1과 6 사이의 원소 출력, 이 때 2개 단위로 건너뛰면서

tensor([0., 1., 2., 3., 4., 5., 6., 7.])
tensor([1., 2., 3.])
tensor([1., 2., 3., 4., 5., 6., 7.])
tensor([0., 1., 2., 3.])
tensor(7.)
tensor([0., 1., 2., 3., 4., 5., 6.])
tensor([1., 3., 5.])


In [93]:
temp2 = torch.Tensor([[1,2,3], [4,5,6]])

print(temp2)
print(temp2[1:])
print(temp2[1:,1:])
print(temp2[1:,0])

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[4., 5., 6.]])
tensor([[5., 6.]])
tensor([4.])


### 3. Tensor element types

add 'dtype' argument to tensor constructors

-> specify the data type that will be contained in the tensor

dtype을 구성하는 것

- possible values the tensor can hold (int, float, ...)
- number of bytes per value(8, 16, 32, ...)

예)

- torch.float32 (= torch.float): 3-bit floating point

- torch.float64 (=torch.double): 64-bit, double-precision floating point

- torch.float64 (=torch.half): 16-bit, half-precision floating point

- torch.float64 (=torch.int): 32-bit integers

- torch.float64 (=torch.long): 64-bit integers

- torch.bool : Boolean

In [94]:
float_points = torch.ones(5, 2, dtype=torch.float32)
int_points = torch.zeros(3, dtype=torch.int64)

print(float_points)
print(int_points)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([0, 0, 0])


In [95]:
# default : float
default_points = torch.Tensor([2, 2])
print(default_points)

tensor([2., 2.])


In [96]:
# find out dtype
print(float_points.dtype)
print(int_points.dtype)
print(default_points)

torch.float32
torch.int64
tensor([2., 2.])


In [97]:
# other forms df specifying dtype

to_int_1 = float_points.int()
print(to_int_1.dtype)

# 'to' checks whether the converstion is necessary and if so, does it.
to_int_2 = float_points.to(torch.int64)
print(to_int_2.dtype)

to_float_1 = int_points.float()
print(to_float_1.dtype)

to_float_2 = int_points.to(dtype=torch.float16)
print(to_float_2.dtype)

torch.int32
torch.int64
torch.float32
torch.float16


### 4. The Tensor API

tensor와 관련된 대부분의 operation은 torch 모듈에 구현되어 있음

예)
- math operations: abs, cos, mean, std, norm, equal, max, ...
- tensor element-wise sum, concat, ...
- random sampling: randn, normal, ...

### 5. Tensor Shape and Reshape

In [98]:
# shape : Returns the size of the tensor

a = torch.Tensor([[1,2,3], [4,5,6]])

print(a)
print(a.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])


In [99]:
# size()

print(a.size())

torch.Size([2, 3])


In [100]:
# Reshape : 주어진 shape로 original tensor에서 데이터를 가져와서 reshape한다

a_reshape = a.reshape(3, 2)
print(a_reshape)
print(a_reshape.shape)

a_reshape_2 = a.reshape(-1, 2)
print(a_reshape_2)
print(a_reshape_2.shape)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
torch.Size([3, 2])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
torch.Size([3, 2])


In [104]:
# # if shape is not compatible with the current shape:
# a_no_reshape = a.reshape(4, 2)

RuntimeError: shape '[4, 2]' is invalid for input of size 6

In [106]:
x = torch.randn(4,4)
print(x)

y = x.view(16)
print(y.size())

z = x.view(-1,8)
print(z.size())

tensor([[ 0.4821, -0.5042,  0.2445,  0.0745],
        [ 0.0171, -0.4981, -0.2321, -0.1388],
        [-0.5204, -0.7755, -0.2535,  0.6298],
        [-0.6216,  0.5818,  0.4613,  0.6636]])
torch.Size([16])
torch.Size([2, 8])


### 6. Transpose

In [108]:
x = torch.randn(1)
print(x)
print(torch.t(x))

y = torch.randn(3)
print(y)
print(y.t())

z = torch.randn(2, 3)
print(z)
print(torch.t(z))

tensor([0.2745])
tensor([0.2745])
tensor([-1.0441,  0.3797,  0.0167])
tensor([-1.0441,  0.3797,  0.0167])
tensor([[ 0.0602, -0.5502, -0.8870],
        [ 0.5980,  1.1640,  0.4441]])
tensor([[ 0.0602,  0.5980],
        [-0.5502,  1.1640],
        [-0.8870,  0.4441]])


In [109]:
w = torch.randn(2, 3)
print(w)
print(torch.transpose(w, 0, 1))

tensor([[ 0.5371, -0.6392, -1.1418],
        [-0.2577, -0.7542, -0.8694]])
tensor([[ 0.5371, -0.2577],
        [-0.6392, -0.7542],
        [-1.1418, -0.8694]])


In [110]:
real_example = torch.randn(64, 128, 768)
print(real_example.shape)
transposed = torch.transpose(real_example, 1, 2)
print(transposed.shape)

torch.Size([64, 128, 768])
torch.Size([64, 768, 128])


### 7. Operations Example

In [111]:
x = torch.ones(1,2)
print(x)
y = torch.ones(5,3)
print(y)

tensor([[1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [113]:
# 
# print(x+y)

In [114]:
y = torch.ones(5, 2)
print(y)

# 1.
print(x+y)

# 2.
print(torch.add(x,y))

# 3. 
result = torch.empty(5,2)
torch.add(x, y, out=result)
print(result)

# 4. inplace
print(y.add_(x))

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]])


### Reference : Moving tensors to the GPU

if you are using Google colaboratory, please set the runtime type to GPUs.

In [115]:
torch.cuda.is_available()

False

In [131]:
!pip install torchvision

     ---------------------------------------- 1.1/1.1 MB 11.5 MB/s eta 0:00:00
     -------------------------------------- 162.5/162.5 MB 8.4 MB/s eta 0:00:00
  Attempting uninstall: torch
    Found existing installation: torch 1.13.0
    Uninstalling torch-1.13.0:
      Successfully uninstalled torch-1.13.0


ERROR: Could not install packages due to an OSError: [WinError 5] 액세스가 거부되었습니다: 'C:\\Users\\user\\AppData\\Local\\Temp\\pip-uninstall-yrass7ig\\libiomp5md.dll'
Consider using the `--user` option or check the permissions.



In [125]:
import torch

In [133]:
# from torch import cuda

In [136]:
# pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html

In [138]:
print(torch.cuda.is_available())

False


In [139]:
# points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

# print(points_gpu)

AssertionError: Torch not compiled with CUDA enabled

In [ ]:
# points = torch.randn(2, 3)
# points_gpu = points.to(device='cuda')

# print(points_gpu)

In [ ]:
# points_gpu_0 = points.to(device='cuda:0')
# print(points_gpu_0)

In [ ]:
# # oprations performed on CPU and GPU

# points = 2 * points
# print(points)

# points_op_gpu = 2* points.to(device='cuda')
# print(points_op_gpu)

# part.3

## MovieLens

In [166]:
import os 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [142]:
path = '../230112/'

In [143]:
os.listdir(path)

['02-1-numpy, pandas와 친해지기.ipynb',
 '02-2-PyTorch-기본.ipynb',
 '03-MovieLens 데이터 - 유저와 영화 그리고 평점 데이터 분석.ipynb',
 '04-MovieLens 데이터 - 영화 기본정보 데이터 분석.ipynb',
 '05-추천시스템 맛보기.ipynb',
 '230112_yewon.ipynb',
 'links.csv',
 'movies.csv',
 'ratings.csv',
 'README.txt',
 'tags.csv']

In [144]:
ratings_df = pd.read_csv(os.path.join(path + 'ratings.csv'), encoding='utf-8')
tags_df = pd.read_csv(os.path.join(path + 'tags.csv'), encoding='utf-8')
movies_df = pd.read_csv(os.path.join(path + 'movies.csv'), index_col='movieId', encoding='utf-8')

- timestamp는 영화에 대한 평점을 기록한 시점. 영화가 처음 출시한 시점이 아니다.

In [145]:
print(ratings_df.shape)
print(ratings_df.head())

(100836, 4)
   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931


In [146]:
print(tags_df.shape)
print(tags_df.head())

(3683, 4)
   userId  movieId              tag   timestamp
0       2    60756            funny  1445714994
1       2    60756  Highly quotable  1445714996
2       2    60756     will ferrell  1445714992
3       2    89774     Boxing story  1445715207
4       2    89774              MMA  1445715200


In [147]:
print(movies_df.shape)
print(movies_df.head())

(9742, 2)
                                      title  \
movieId                                       
1                          Toy Story (1995)   
2                            Jumanji (1995)   
3                   Grumpier Old Men (1995)   
4                  Waiting to Exhale (1995)   
5        Father of the Bride Part II (1995)   

                                              genres  
movieId                                               
1        Adventure|Animation|Children|Comedy|Fantasy  
2                         Adventure|Children|Fantasy  
3                                     Comedy|Romance  
4                               Comedy|Drama|Romance  
5                                             Comedy  


## 평점 데이터의 기초 통계량

In [148]:
n_unique_users = len(ratings_df['userId'].unique())
print(n_unique_users)

610


In [149]:
n_unique_movies = len(ratings_df['movieId'].unique())
print(n_unique_movies)

9724


In [151]:
print('평점의 평균: ', ratings_df['rating'].mean())
print('평점의 표준편차: ', ratings_df['rating'].std())

평점의 평균:  3.501556983616962
평점의 표준편차:  1.0425292390605359


In [159]:
ratings_df.columns

Index(['userId', 'movieId', 'rating', 'timestamp'], dtype='object')

In [152]:
ratings_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype  
---  ------     --------------   -----  
 0   userId     100836 non-null  int64  
 1   movieId    100836 non-null  int64  
 2   rating     100836 non-null  float64
 3   timestamp  100836 non-null  int64  
dtypes: float64(1), int64(3)
memory usage: 3.1 MB


In [153]:
ratings_df.describe()

userId        movieId         rating     timestamp
count  100836.000000  100836.000000  100836.000000  1.008360e+05
mean      326.127564   19435.295718       3.501557  1.205946e+09
std       182.618491   35530.987199       1.042529  2.162610e+08
min         1.000000       1.000000       0.500000  8.281246e+08
25%       177.000000    1199.000000       3.000000  1.019124e+09
50%       325.000000    2991.000000       3.500000  1.186087e+09
75%       477.000000    8122.000000       4.000000  1.435994e+09
max       610.000000  193609.000000       5.000000  1.537799e+09

In [154]:
ratings_df.isnull().sum()

userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

### Pandas의 GroupBy 사용하기

In [157]:
ratings_df.groupby(['userId','rating']).size()

userId  rating
1       1.0         1
        2.0         5
        3.0        26
        4.0        76
        5.0       124
                 ... 
610     3.0       230
        3.5       315
        4.0       286
        4.5       148
        5.0       180
Length: 3976, dtype: int64

- userid와 rating을 기준으로 기초 통계량

In [160]:
ratings_df.groupby(['userId']).mean()

movieId    rating     timestamp
userId                                      
1        1854.603448  4.366379  9.649856e+08
2       70350.275862  3.948276  1.445715e+09
3        7058.384615  2.435897  1.306464e+09
4        1982.129630  3.555556  9.658643e+08
5         343.840909  3.636364  8.474351e+08
...              ...       ...           ...
606      9692.197309  3.657399  1.179512e+09
607      1860.636364  3.786096  9.647841e+08
608      4502.605295  3.134176  1.122668e+09
609       483.162162  3.270270  8.472210e+08
610     49590.231183  3.688556  1.489454e+09

[610 rows x 3 columns]

In [162]:
userid_rating_df = pd.DataFrame({'count': ratings_df.groupby(['userId', 'rating']).size()})
userid_rating_df = userid_rating_df.reset_index()
userid_rating_df.head(10)

userId  rating  count
0       1     1.0      1
1       1     2.0      5
2       1     3.0     26
3       1     4.0     76
4       1     5.0    124
5       2     2.0      1
6       2     2.5      1
7       2     3.0      4
8       2     3.5      4
9       2     4.0      9

In [163]:
user_info = ratings_df.groupby('userId')['movieId'].count()

In [164]:
user_info

userId
1       232
2        29
3        39
4       216
5        44
       ... 
606    1115
607     187
608     831
609      37
610    1302
Name: movieId, Length: 610, dtype: int64

In [165]:
user_info.describe()

count     610.000000
mean      165.304918
std       269.480584
min        20.000000
25%        35.000000
50%        70.500000
75%       168.000000
max      2698.000000
Name: movieId, dtype: float64

In [167]:
sns.displot(user_info.values)

: 

: 