# Part4_2 Randomforest

In [1]:
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
# 현재경로 확인
os.getcwd()

'c:\\Users\\user\\Documents\\ML\\wk2'

In [3]:
data = pd.read_csv("./otto_train.csv")
data.head()

id  feat_1  feat_2  feat_3  feat_4  feat_5  feat_6  feat_7  feat_8  feat_9  \
0   1       1       0       0       0       0       0       0       0       0   
1   2       0       0       0       0       0       0       0       1       0   
2   3       0       0       0       0       0       0       0       1       0   
3   4       1       0       0       1       6       1       5       0       0   
4   5       0       0       0       0       0       0       0       0       0   

   ...  feat_85  feat_86  feat_87  feat_88  feat_89  feat_90  feat_91  \
0  ...        1        0        0        0        0        0        0   
1  ...        0        0        0        0        0        0        0   
2  ...        0        0        0        0        0        0        0   
3  ...        0        1        2        0        0        0        0   
4  ...        1        0        0        0        0        1        0   

   feat_92  feat_93   target  
0        0        0  Class_1  
1        0        0  Class_1  
2        0        0  Class_1  
3        0        0  Class_1  
4        0        0  Class_1  

[5 rows x 95 columns]

In [4]:
'''
id : 고유 아이디
feat_1 ~ feat_93 : 설명변수
target : 타겟변수 (1~9)
'''

'\nid : 고유 아이디\nfeat_1 ~ feat_93 : 설명변수\ntarget : 타겟변수 (1~9)\n'

In [5]:
nCar = data.shape[0] # 데이터 개수
nVar = data.shape[1] # 변수 개수
print('nCar : %d' % nCar, 'nVar : %d' % nVar)

nCar : 61878 nVar : 95


## 의미 없는 변수 제거

In [6]:
data = data.drop(['id'], axis= 1)

## 타겟 변수의 문자열을 숫자로 변환

In [7]:
mapping_dict = {}

for nm in range(9):
    mapping_dict[f'Class_{nm+1}'] = nm+1

In [8]:
after_mapping_target = data['target'].apply(lambda x : mapping_dict[x])

In [9]:
after_mapping_target

0        1
1        1
2        1
3        1
4        1
        ..
61873    9
61874    9
61875    9
61876    9
61877    9
Name: target, Length: 61878, dtype: int64

## 설명변수와 타겟변수를 분리, 학습데이터와 평가데이터 분리

In [10]:
feature_columns = list(data.columns.difference(['target']))
X = data[feature_columns]
y = after_mapping_target
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.2, random_state=0)
print(train_X.shape, test_X.shape, train_y.shape, test_y.shape)

(49502, 93) (12376, 93) (49502,) (12376,)


## 학습 데이터를 랜덤포레스트 모형에 적합 후 평가 데이터로 검증

In [11]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
random_forest_model1 = RandomForestClassifier(n_estimators=20, # 20번 추정
                                                max_depth=5, #트리 최대 깊이 5 -> 너무 깊어지면  과대적합이 일어난다.(정확도가 100에 가까워짐) 
                                                            # -> train에는 좋아도 사용하기에는 부적합
                                                random_state= 40) #시드값 고정
model1 = random_forest_model1.fit(train_X, train_y) # 학습 진행
predict1 = model1.predict(test_X) # 평가 데이터 예측
print("Accuracy: %.2f" % (accuracy_score(test_y, predict1) * 100), "%") # 정확도 계산 (test_y : 정답, predict : 모델이 추출한 답)

Accuracy: 60.02 %


## 트리를 많이 만들어보기

In [12]:
random_forest_model2 = RandomForestClassifier(n_estimators=300, # 300번 추정
                                                max_depth=5, #트리 최대 깊이 5
                                                random_state= 40) #시드값 고정
model2 = random_forest_model2.fit(train_X, train_y) # 학습 진행
predict2 = model2.predict(test_X) # 평가 데이터 예측
print("Accuracy: %.2f" % (accuracy_score(test_y, predict2) * 100), "%") # 정확도 계산

# 큰 차이가 없다

Accuracy: 59.80 %


## 트리의 깊이 늘이기

In [13]:
random_forest_model3 = RandomForestClassifier(n_estimators=300, # 300번 추정
                                                max_depth=20, #트리 최대 깊이 20
                                                random_state= 40) #시드값 고정
model3 = random_forest_model3.fit(train_X, train_y) # 학습 진행
predict3 = model3.predict(test_X) # 평가 데이터 예측
print("Accuracy: %.2f" % (accuracy_score(test_y, predict3) * 100), "%") # 정확도 계산

# accuracy_score가 80정도 나오면 쓸만하다(경험학적인 관점)

Accuracy: 77.86 %


## 트리의 깊이 최대로 늘려보기

In [14]:
random_forest_model4 = RandomForestClassifier(n_estimators=300, # 300번 추정
                                                max_depth=100, #트리 최대 깊이 100
                                                random_state= 40) #시드값 고정
model4 = random_forest_model4.fit(train_X, train_y) # 학습 진행
predict4 = model4.predict(test_X) # 평가 데이터 예측
print("Accuracy: %.2f" % (accuracy_score(test_y, predict4) * 100), "%") # 정확도 계산

Accuracy: 80.98 %


# Part4_4 Ensemble

In [15]:
# import os
# import pandas as pd
# import numpy as pd
# from sklearn.model_selection import train_test_split
# from sklearn.metrics import accuracy_score

In [16]:
os.getcwd()

'c:\\Users\\user\\Documents\\ML\\wk2'

In [17]:
df = pd.read_csv("./otto_train.csv")
df.head()

id  feat_1  feat_2  feat_3  feat_4  feat_5  feat_6  feat_7  feat_8  feat_9  \
0   1       1       0       0       0       0       0       0       0       0   
1   2       0       0       0       0       0       0       0       1       0   
2   3       0       0       0       0       0       0       0       1       0   
3   4       1       0       0       1       6       1       5       0       0   
4   5       0       0       0       0       0       0       0       0       0   

   ...  feat_85  feat_86  feat_87  feat_88  feat_89  feat_90  feat_91  \
0  ...        1        0        0        0        0        0        0   
1  ...        0        0        0        0        0        0        0   
2  ...        0        0        0        0        0        0        0   
3  ...        0        1        2        0        0        0        0   
4  ...        1        0        0        0        0        1        0   

   feat_92  feat_93   target  
0        0        0  Class_1  
1        0        0  Class_1  
2        0        0  Class_1  
3        0        0  Class_1  
4        0        0  Class_1  

[5 rows x 95 columns]

In [18]:
cCar = data.shape[0]
cVar = data.shape[1]
print('cCar: %d' % cCar, 'cVar: %d' % cVar)

cCar: 61878 cVar: 94


## 의미가 없다고 판단되는 변수 제거

In [19]:
df = df.drop(['id'], axis=1)

## 타겟 변수의 문자열을 숫자로 변환

In [20]:
mapping_dict = {}

for nm in range(9):
    mapping_dict[f'Class_{nm+1}'] = nm+1

## 타겟 변수의 문자열을 숫자로 변환

In [21]:
after_mapping_target = data.target.apply(lambda x : mapping_dict[x])

## 설명변수와 타겟변수를 분리, 학습데이터와 평가데이터 분리

In [22]:
feature_columns = list(data.columns.difference(['target']))
X = data[feature_columns]
y = after_mapping_target
train_x, test_x, train_y, test_y = train_test_split(X, y, test_size=0.2, random_state=40)
print(train_x.shape, test_x.shape, train_y.shape, test_y.shape)

(49502, 93) (12376, 93) (49502,) (12376,)


## 1. XGBoost

꼭 이 방법을 사용하지 않아도 괜찮다

In [23]:
import xgboost as xgb
import time
start = time.time() # 시작 시간 지정
xgb_dtrain = xgb.DMatrix(data = train_x, label = train_y) # 학습 데이터를 XGBoost 모델에 맞게 변환
xgb_dtest = xgb.DMatrix(data = test_x) # 평가 데이터를 XGBoost 모델에 맞게 변환
xgb_param = {'max_depth' : 10,
            'learning_rate' : 0.01, # Stepsize
            'n_estimators' : 100, # Number of trees, 트리 생성 개수
            'objective' : 'multi:softmax', # 목적 함수
            'num_class' : len(set(train_y)) +1 # 파라미터 추가, Label must be in (0, num_class) -> num_class보다 1 커야함.
            }
xgb_model = xgb.train(params = xgb_param, dtrain= xgb_dtrain)
xgb_model_predict = xgb_model.predict(xgb_dtest)
print("Accuracy : %.2f" % (accuracy_score(test_y, xgb_model_predict) * 100), "%") # 정확도 % 계산
print("Time : %.2f" % (time.time() - start), "seconds") # 코드 실행 시간 계산

[17:27:28] WARNING: C:/buildkite-agent/builds/buildkite-windows-cpu-autoscaling-group-i-030221e36e1a46bfb-1/xgboost/xgboost-ci-windows/src/learner.cc:767: 
Parameters: { "n_estimators" } are not used.

Accuracy : 75.57 %
Time : 1.88 seconds


In [24]:
xgb_model_predict

array([9., 6., 6., ..., 8., 8., 9.], dtype=float32)

## 2. LightGBM

In [25]:
!pip install lightgbm

In [26]:
import lightgbm as lgb
start = time.time()
lgb_dtrain = lgb.Dataset(data = train_x, label = train_y) # 학습데이터를 LightGBM 모델에 맞게 변환
lgb_param = {'max_depth' : 10, # 트리 깊이
            'learning_rate' : 0.1, # Step size
            'n_estimators' : 100, # Number of trees, 트리생성개수
            'objective' : 'multiclass', # 목적 함수
            'num_class' : len(set(train_y)) +1 # 파라미터 추가, Label must be in (0, num_class) -> num_class보다 1 커야함.
            }
lgb_model = lgb.train(params= lgb_param, train_set= lgb_dtrain)
lgb_model_predict = np.argmax(lgb_model.predict(test_x), axis = 1) # 평가 데이터 예측, Softmax의 결과값 중 가장 큰 값의 Label로 예측
print("Accuracy : %.2f" % (accuracy_score(test_y, lgb_model_predict) * 100), "%") # 정확도 % 계산
print("Time : %.2f" % (time.time() - start), "seconds") # 코드 실행 시간 계산

c:\ProgramData\Anaconda3\lib\site-packages\lightgbm\engine.py:177: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")


[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005475 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 3140
[LightGBM] [Info] Number of data points in the train set: 49502, number of used features: 93
[LightGBM] [Info] Start training from score -34.538776
[LightGBM] [Info] Start training from score -3.444588
[LightGBM] [Info] Start training from score -1.343082
[LightGBM] [Info] Start training from score -2.041661
[LightGBM] [Info] Start training from score -3.145422
[LightGBM] [Info] Start training from score -3.110832
[LightGBM] [Info] Start training from score -1.482623
[Ligh

In [27]:
lgb_model_predict

array([9, 6, 6, ..., 8, 8, 9], dtype=int64)

## 3. Catboost

In [28]:
!pip install catboost

In [29]:
import catboost as cb
start = time.time()
cb_dtrain = cb.Pool(data = train_x, label = train_y) # 학습데이터를 LightGBM 모델에 맞게 변환
cb_param = {'max_depth' : 10, # 트리 깊이
            'learning_rate' : 0.1, # Step size
            'n_estimators' : 100, # Number of trees, 트리생성개수
            'eval_metric' : 'Accuracy', # 평가 척도
            'loss_function' : 'MultiClass' # 손실 함수, 목적 함수
            }
cb_model = cb.train(pool= cb_dtrain, params= cb_param)
cb_model_predict = np.argmax(cb_model.predict(test_x), axis = 1) # 평가 데이터 예측, Softmax의 결과값 중 가장 큰 값의 Label로 예측
print("Accuracy : %.2f" % (accuracy_score(test_y, cb_model_predict) * 100), "%") # 정확도 % 계산
print("Time : %.2f" % (time.time() - start), "seconds") # 코드 실행 시간 계산

0:	learn: 0.5955921	total: 423ms	remaining: 41.9s
1:	learn: 0.6352673	total: 677ms	remaining: 33.2s
2:	learn: 0.6531049	total: 917ms	remaining: 29.6s
3:	learn: 0.6581956	total: 1.17s	remaining: 28.1s
4:	learn: 0.6660741	total: 1.44s	remaining: 27.3s
5:	learn: 0.6715890	total: 1.69s	remaining: 26.5s
6:	learn: 0.6766191	total: 1.95s	remaining: 25.9s
7:	learn: 0.6813058	total: 2.19s	remaining: 25.2s
8:	learn: 0.6868409	total: 2.46s	remaining: 24.9s
9:	learn: 0.6916488	total: 2.74s	remaining: 24.7s
10:	learn: 0.6960729	total: 3.01s	remaining: 24.4s
11:	learn: 0.6991435	total: 3.28s	remaining: 24s
12:	learn: 0.7013050	total: 3.55s	remaining: 23.8s
13:	learn: 0.7032645	total: 3.8s	remaining: 23.4s
14:	learn: 0.7063351	total: 4.06s	remaining: 23s
15:	learn: 0.7092643	total: 4.32s	remaining: 22.7s
16:	learn: 0.7114662	total: 4.57s	remaining: 22.3s
17:	learn: 0.7135671	total: 4.8s	remaining: 21.9s
18:	learn: 0.7169003	total: 5.05s	remaining: 21.5s
19:	learn: 0.7200719	total: 5.3s	remaining: 21.

In [30]:
cb_model.predict(test_x)

array([[ 0.21253034,  0.65684363,  0.07120576, ..., -0.6950527 ,
         0.52780085,  2.47129728],
       [-0.26592681, -0.9386558 , -1.55880405, ..., -0.34333762,
         0.44284098, -0.57560756],
       [ 1.06973695, -1.95046866, -2.31159984, ..., -0.37514737,
         2.35229294,  0.93325542],
       ...,
       [ 1.09505722, -0.89480159, -0.84397374, ..., -1.1409345 ,
         3.64063393,  2.49051575],
       [ 1.02570074, -1.7024878 , -2.09985945, ...,  0.1288898 ,
         6.92558706,  0.47816423],
       [ 1.94838412, -1.00317417, -1.60780683, ..., -0.3745579 ,
        -0.0301398 ,  3.4741448 ]])

# 앙상블

In [31]:
data = pd.read_csv("./kc_house_data.csv")
data.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7      1180.0              0   
1      7242     2.0           0     0  ...      7      2170.0            400   
2     10000     1.0           0     0  ...      6       770.0              0   
3      5000     1.0           0     0  ...      7      1050.0            910   
4      8080     1.0           0     0  ...      8      1680.0              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [32]:
data = data.drop(['id', 'date', 'zipcode', 'lat','long'], axis=1)

In [33]:
data.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0         3       1.00         1180      5650     1.0           0   
1  538000.0         3       2.25         2570      7242     2.0           0   
2  180000.0         2       1.00          770     10000     1.0           0   
3  604000.0         4       3.00         1960      5000     1.0           0   
4  510000.0         3       2.00         1680      8080     1.0           0   

   view  condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0     0          3      7      1180.0              0      1955             0   
1     0          3      7      2170.0            400      1951          1991   
2     0          3      6       770.0              0      1933             0   
3     0          5      7      1050.0            910      1965             0   
4     0          3      8      1680.0              0      1987             0   

   sqft_living15  sqft_lot15  
0           1340        5650  
1           1690        7639  
2           2720        8062  
3           1360        5000  
4           1800        7503

In [34]:
feature_columns = list(data.columns.difference(['price']))
X = data[feature_columns]
y = data['price']

train_x, test_x, train_y, test_y = train_test_split(X, y, test_size=0.3, random_state= 40)
print(train_x.shape, test_x.shape, train_y.shape, test_y.shape)

(15129, 15) (6484, 15) (15129,) (6484,)


In [35]:
# import lightgbm as lgb
start = time.time()
lgb_dtrain = lgb.Dataset(data = train_x, label = train_y)
lgb_param = {'max_depth' : 10,
            'learning_reat': 0.01,
            'n_estimators' : 500,
            'objective' : 'regression'}
lgb_model = lgb.train(params = lgb_param, train_set = lgb_dtrain)
# lgb_model_predict = np.argmax(lgb_model.predict(test_x), axis = 0)

# print("Accuracy: %.2f" % (accuracy_score(test_y, lgb_model_predict) * 100), "%") # 정확도 % 계산
# print("Time: %.2f" % (time.time() - start), "seconds") # 코드 실행 시간 계산

[LightGBM] [Warning] Unknown parameter: learning_reat
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Unknown parameter: learning_reat
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000769 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1745
[LightGBM] [Info] Number of data points in the train set: 15129, number of used features: 15
[LightGBM] [Info] Start training from score 539524.963712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain

c:\ProgramData\Anaconda3\lib\site-packages\lightgbm\engine.py:177: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")


[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No f

In [36]:
lgb_model

In [37]:
from sklearn.metrics import mean_squared_error, r2_score
from math import sqrt

sqrt(mean_squared_error(lgb_model.predict(test_x),test_y))

180719.68562552982

## Ensemble의 Ensemble

In [38]:
import random
baggin_predict_result = [] # 빈 리스트 형성
for _ in range(10):
    data_index = [data_index for data_index in range(train_x.shape[0])] # 학습데이터의 인덱스를 리스트로 변환
    random_data_index = np.random.choice(data_index, train_x.shape[0]) 
    print(len(set(random_data_index)))
    lgb_dtrain = lgb.Dataset(data = train_x.iloc[random_data_index,], label = train_y.iloc[random_data_index,])
    lgb_param = {'max_depth' : 14, # 트리 깊이
                'learning_rate' : 0.01, # Step size
                'n_estimators' : 500, # 트리 생성 개수
                'objective' : 'regression' # 목적 : 회귀분석 (?)
                }
    lgb_model = lgb.train(params = lgb_param, train_set = lgb_dtrain)
    predict1 = lgb_model.predict(test_x)
    baggin_predict_result.append(predict1)

9595
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000566 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1719
[LightGBM] [Info] Number of data points in the train set: 15129, number of used features: 15
[LightGBM] [Info] Start training from score 537922.040056


c:\ProgramData\Anaconda3\lib\site-packages\lightgbm\engine.py:177: UserWarning: Found `n_estimators` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")


9559
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000530 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1706
[LightGBM] [Info] Number of data points in the train set: 15129, number of used features: 15
[LightGBM] [Info] Start training from score 531900.921872
9567
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000515 seconds.
You can set `

In [39]:
baggin_predict_result

[array([1249185.57878622,  643352.19925481,  380703.77508608, ...,
         291425.19430134,  730695.03675299,  995295.1343749 ]),
 array([1256807.18397116,  593413.34985371,  378487.71846895, ...,
         281064.16398685,  736295.16736705,  972742.26328592]),
 array([1206989.5349773 ,  618486.74293827,  394276.43039988, ...,
         295869.6900848 ,  741020.21924202, 1008184.14668011]),
 array([1137394.44055702,  615642.45328396,  401472.8251325 , ...,
         281271.10073069,  742685.56752922,  985060.22036848]),
 array([1216020.50480135,  635812.2423234 ,  393652.95602299, ...,
         275120.4610991 ,  706664.01033949,  931682.04318727]),
 array([1135113.88004514,  603760.04051463,  386518.36641   , ...,
         299464.95012091,  713511.46939597,  979794.94946019]),
 array([1256296.0612623 ,  628941.49584051,  378427.87066729, ...,
         286689.93440324,  710503.87195076, 1028372.88265254]),
 array([1293186.37932458,  632778.76950349,  373369.18149231, ...,
         290914.

In [40]:
# Bagging 을 바탕으로 예측한 결과값에 대한 평균을 계싼
baggin_predict = [] # 빈 list 형성
for lst2_index in range(test_x.shape[0]): # test data의 개수만큼 반복
    temp_predict = [] # 임시로 빈 리스트 형성
    for lst_index in range(len(baggin_predict_result)): # Bagging 결과 리스트 반복
        temp_predict.append(baggin_predict_result[lst_index][lst2_index]) # 각 Bagging 결과 예측한 값 중 같은 인덱스를 리스트에 저장
    baggin_predict.append(np.mean(temp_predict)) # 해당 인덱스의 30개의 결과값에 대한 평균을 최종 리스트에 추가

In [41]:
# 예측한 결과값들의 평균을 계산하여 실제 테스트 데이트의 타겟변수와 비교하여 성능 평가

print('RMSE : {}'.format(sqrt(mean_squared_error(baggin_predict, test_y)))) # RMSE

RMSE : 177526.62235590428


In [42]:
baggin_predict

[1217090.9475483347,
 619362.3972365044,
 388662.72231473273,
 430429.7902139987,
 460092.8540241138,
 698944.5809055403,
 1028101.0965050369,
 659899.6987785941,
 451248.56729572604,
 500615.82193357975,
 414338.4521542303,
 336292.6748252989,
 425867.2687308929,
 442095.20852764975,
 280039.24516915093,
 577654.8307805189,
 420390.06885322894,
 430034.90359400195,
 719683.2833766793,
 452954.3283386092,
 359127.47777827666,
 474938.4101559903,
 1064780.6149914484,
 251657.8730761384,
 662012.0045439231,
 321520.2618119733,
 762216.1591135275,
 400803.61873696,
 982248.9107709052,
 973453.8583206963,
 453597.9383819311,
 632678.1993060864,
 394091.88714393904,
 399201.44154121185,
 439248.6925081988,
 439384.34064877266,
 277425.29856596125,
 505850.82595093467,
 448287.1834931977,
 335667.5233108675,
 705384.8202239738,
 367963.2522382465,
 300859.471710377,
 626657.5466628904,
 405005.1901360684,
 774672.8604523751,
 244046.11199848875,
 531033.473065442,
 433395.28093456326,
 14835